name: Swift check API breaks

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze-api-breakage:

    runs-on: [swift-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Extract default SPM library target
      id: spm_target
      run: |
        SPM_DEFAULT_TARGET=$(swift package dump-package | jq -r '.products | .[] | select(.type | has("library")) | .name' | head -1)
        echo "::set-output name=spmlibrarytarget::$SPM_DEFAULT_TARGET"
    - name: Build
      if: ${{ steps.spm_target.outputs.spmlibrarytarget }}
      run: swift build
    - name: Analyze API breakage
      if: ${{ steps.spm_target.outputs.spmlibrarytarget }}
      run: swift package diagnose-api-breaking-changes origin/main --targets ${{ steps.spm_target.outputs.spmlibrarytarget }}
