name: Swift build and test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build-benchmark:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]

    steps:
    - uses: actions/checkout@v3
    - name: Install jemalloc Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libjemalloc-dev
    - name: Install jemalloc macOS
      if: matrix.os == 'macos-12'
      run: brew install jemalloc
    - name: Build
      run: swift build
    - name: Run tests on Linux
      if: matrix.os == 'ubuntu-latest'
      run: swift test 
